### PR TITLE
Decrease lane height

### LINKED ISSUE #49: Decrease lane heights by 1/2 or 1/3 (Brian's feedback)

### PR DESCRIPTION
**Pull request by kartikcho**
As per Brian's feedback in the recent internal meeting, this PR reduces lane sizes to 1/3rd it's original size.
Resolves #49 

### Screenshots to compare sizes
Original size:
Screenshot (181)

2/3 original size (Also the size of lane in this PR):
image

Half the original size:
image

### CODE REVIEW

**Comment by kartikcho** [comment]
Pinging @bvaughn to decide which size looks better and if the suspense marks should be made smaller (although I don't think so)

**Comment by bvaughn** [comment]
Hey @kartik918 thanks for the ping :smile:

I think the original mock had ~11px high rows (with a 1px border) - which looks like your 2/3 size screenshot above.

The dots (e.g. state update, suspend, etc) look better in the first mock though, where they're smaller. In my mock they were 10px high.

Can we just use those sizes? (11px and 10px)

scheduling-profiler-lanes-mock-3

**Comment by kartikcho** [comment]
Sure, thanks!

**Comment by kartikcho** [comment]
This is how the dots look like in the PR, I took the screenshot while testing with other sizes after committing. 

image

**Comment by bvaughn** [comment]
The dots look nice! The border lines look a bit blurry, probably b'c they're sub-pixel size. Why is this out of curiosity? Seems like 1px is good for lines.

**Comment by kartikcho** [comment]
> Why is this out of curiosity? Seems like 1px is good for lines.

They looked kinda big compared to the smaller lane size now, also reduced it 1/3 along with the rest of the graph (although not exactly accurate).
I'll revert it!

**Comment by bvaughn** [comment]
Ah I gotcha 🙂  Personal preference is to avoid sub-pixel sizes for borders. It makes them blurry and less crisp on lower density monitors.

**Review by taneliang — APPROVED** [review]
LGTM! I've run Prettier to fix the code formatting.

Some screenshots with my larger profile:

Before:

image

After:

image

**Pull request merged**
